// Generated by CoffeeScript 1.3.3
(function() {
  var contains, delay, simpleFactory, _;

  _ = require('underscore');

  delay = exports.delay = function(t, f) {
    return setTimeout(f, t);
  };

  contains = exports.contains = function(item, text) {
    return text.indexOf(item) !== -1;
  };

  simpleFactory = exports.simpleFactory = function(Obj, params) {
    if (params) {
      if (_.isString(params)) {
        return new Obj(params);
      } else {
        return params;
      }
    } else {
      return new Obj();
    }
  };

}).call(this);
