// Generated by CoffeeScript 1.3.3
(function() {
  var BinaryTree, Memory, Stream, YAML, contains, delay, error, events, fs, getFormat, inspect, log, moment, snappy, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  Stream = require('stream').Stream;

  events = require('events');

  fs = require('fs');

  moment = require('moment');

  YAML = require('libyaml');

  snappy = require('snappy');

  _ref1 = require('../misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains;

  BinaryTree = require('../misc/btree');

  Memory = require('./memory');

  getFormat = function(path) {
    var _base;
    if (!path) {
      return "UNKNOW";
    }
    switch (typeof path.split === "function" ? typeof (_base = path.split(".").slice(-1)[0]).toLowerCase === "function" ? _base.toLowerCase() : void 0 : void 0) {
      case "js":
      case "json":
        return "JSON";
      case "yml":
      case "yaml":
        return "YAML";
      case "smp":
      case "sample":
        return "SAMPLER";
      default:
        return "UNKNOW";
    }
  };

  /* TODO use async, streaming file reading:
  
  writeStream = fs.createWriteStream(__dirname + "/outFile.txt");
  // every time "data" is read, this event fires
  readStream.on('data', function(textData) {
    console.log("Found some text!");
    writeStream.write(textData);
  });
  
  // the reading is finished...
  readStream.on('close', function () {
    writeStream.end(); // ...close up the write, too!
    console.log("I finished.");
  });
  
  
  "Partially buffered access methods are different. 
  They do not treat data input as a discrete event, 
  but rather as a series of events which occur as 
  the data is being read or written. They allow us
  to access data as it is being read from 
  disk/network/other I/O.
  Partially buffered methods, such as readSync() 
  and read() allow us to specify the size of the
  buffer, and read data in small chunks. They
  allow for more control (e.g. reading a file in
  non-linear order by skipping back and forth in
  the file)." (from http://book.mixu.net/ch9.html)
  */


  module.exports = (function(_super) {

    __extends(exports, _super);

    function exports(path, options) {
      var k, v,
        _this = this;
      this.path = path;
      this._writeEvent = __bind(this._writeEvent, this);

      this.save = __bind(this.save, this);

      this.autosave = __bind(this.autosave, this);

      exports.__super__.constructor.call(this);
      this.config = {
        autosave: 500,
        filename: function() {}
      };
      for (k in options) {
        v = options[k];
        this.config[k] = v;
      }
      this.buff = [];
      this.buffMax = 1;
      this.isWriting = false;
      this.flushing = {
        version: 1,
        saved: 0
      };
      this.format = getFormat(this.path);
      switch (this.format) {
        case "YAML":
          log("using YAML");
          this.saveSnapshot = YAML.writeFile;
          break;
        case "JSON":
          log("using JSON");
          this.saveSnapshot = function(path, data, cb) {
            var dumpString;
            dumpString = JSON.stringify(data);
            return fs.writeFile(path, dumpString, function(err) {
              return cb(err);
            });
          };
          break;
        case "SAMPLER":
          this.saveSnapshot = function(path, data, cb) {
            var compressed, dumpString;
            dumpString = JSON.stringify(data);
            compressed = snappy.compressSync(dumpString);
            return fs.writeFile(path, compressed, function(err) {
              return cb(err);
            });
          };
          break;
        default:
          log("unknow format: " + this.format);
          throw "unknow format: " + this.format;
          return;
      }
      this.autosave();
    }

    exports.prototype._load = function(path, cb) {
      if (cb == null) {
        cb = function() {};
      }
    };

    exports.prototype.autosave = function() {
      var _this = this;
      log("AUTOSAVING..");
      delay(0, function() {
        return _this.save();
      });
      return delay(this.config.autosave, function() {
        return _this.autosave();
      });
    };

    exports.prototype.save = function() {
      var event, snapshot, version, _i, _len, _ref2,
        _this = this;
      if (this.isWriting) {
        return;
      }
      this.isWriting = true;
      snapshot = {
        events: []
      };
      this.buff = [];
      _ref2 = this.events;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        event = _ref2[_i];
        snapshot.events.push([0 + event.timestamp, event.data]);
        log("AUTOSAVED");
      }
      version = 0 + this.flushing.version;
      this.flushing.version++;
      this.saveSnapshot(this.path, snapshot, function(err) {
        _this.flushing.saved = version;
        _this.isWriting = false;
        if (err) {
          return _this.emit('error', err);
        } else {
          return _this.emit('flushed', version);
        }
      });
      return false;
    };

    exports.prototype._writeEvent = function(event) {
      var _this = this;
      delay(0, function() {
        _this.events.push(event);
        return _this.buff.push(event);
      });
      return true;
    };

    return exports;

  })(Memory);

}).call(this);
