// Generated by CoffeeScript 1.3.3
(function() {
  var BinaryNode;

  BinaryNode = (function() {

    function BinaryNode(event) {
      this.event = event;
      this.left = null;
      this.right = null;
    }

    return BinaryNode;

  })();

  module.exports = (function() {

    function exports(rootEvent) {
      this.root = new BinaryNode(rootEvent);
      this.count = 1;
    }

    exports.prototype.push = function(event) {
      var newNode, node;
      newNode = new BinaryNode(event);
      node = this.root;
      while (true) {
        if (newNode.event.timestamp >= node.event.timestamp) {
          if (node.right === null) {
            node.right = newNode;
            break;
          } else {
            node = node.right;
          }
        } else {
          if (node.left === null) {
            node.left = newNode;
            break;
          } else {
            node = node.left;
          }
        }
      }
      return this.count++;
    };

    exports.prototype.walk = function(callback) {
      return this.walkFromNode(callback, this.root);
    };

    exports.prototype.walkFromNode = function(callback, node) {
      if (node.left !== null) {
        this.walkFromNode(callback, node.left);
      }
      callback(node);
      if (node.right !== null) {
        return this.walkFromNode(callback, node.right);
      }
    };

    exports.prototype.toString = function() {
      var timestamps;
      timestamps = [];
      this.walk(function(node) {
        return timestamps.push(node.event.timestamp);
      });
      return timestamps.join(', ');
    };

    return exports;

  })();

}).call(this);
