// Generated by CoffeeScript 1.3.3
(function() {
  var contains, delay, error, events, inspect, log, moment, stores, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  events = require('events');

  moment = require('moment');

  _ref1 = require('./misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains;

  stores = require('./stores');

  module.exports = (function(_super) {

    __extends(exports, _super);

    function exports(url, options) {
      var k, path, v,
        _this = this;
      if (url == null) {
        url = "";
      }
      this.write = __bind(this.write, this);

      this.length = __bind(this.length, this);

      this.config = {
        autosave: 1000
      };
      for (k in options) {
        v = options[k];
        this.config[k] = v;
      }
      this.store = new stores.Memory(this.config);
      if (contains("file://", url)) {
        path = url.split("file://")[1];
        this.store = new stores.File(path, this.config);
      }
      this.store.on('error', function(version, err) {
        error("Record: @store sent us an error: " + err);
        return _this.emit('error', {
          version: version,
          err: err
        });
      });
      this.store.on('flushed', function(version) {
        return _this.emit('flushed');
      });
    }

    exports.prototype.length = function() {
      return this.store.length();
    };

    exports.prototype.write = function(timestamp, data) {
      return this.store.write(timestamp, data);
    };

    return exports;

  })(events.EventEmitter);

}).call(this);
