// Generated by CoffeeScript 1.3.3
(function() {
  var Record, simple, stream;

  stream = require('./api/stream');

  simple = require('./api/simple');

  Record = require('./record');

  exports.Record = Record;

  exports.SimpleRecorder = simple.Recorder;

  exports.SimplePlayer = simple.Player;

  exports.StreamRecorder = stream.Recorder;

  exports.StreamPlayer = stream.Player;

}).call(this);
