// Generated by CoffeeScript 1.3.3
(function() {
  var Cursor, Record, Stream, contains, delay, error, inspect, log, moment, simpleFactory, _, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  Stream = require('stream').Stream;

  _ = require('underscore');

  moment = require('moment');

  _ref1 = require('./misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains, simpleFactory = _ref1.simpleFactory;

  Record = require('./record');

  Cursor = require('./cursor');

  exports.Recorder = (function() {

    function Recorder(url) {
      if (url == null) {
        url = false;
      }
      this.writeAt = __bind(this.writeAt, this);

      this.write = __bind(this.write, this);

      this.record = simpleFactory(Record, url);
    }

    Recorder.prototype.write = function(data, status) {
      if (status == null) {
        status = function() {};
      }
      return this.record.write(moment(), data, status);
    };

    Recorder.prototype.writeAt = function(timestamp, data, status) {
      if (status == null) {
        status = function() {};
      }
      return this.record.write(timestamp, data, status);
    };

    return Recorder;

  })();

  exports.Player = (function() {

    function Player(url, options) {
      var k, v,
        _this = this;
      this.config = {
        speed: 1.0,
        autoplay: true,
        timestamp: false,
        looped: false,
        onData: function(tm, data) {},
        onEnd: function() {},
        onError: function(err) {}
      };
      for (k in options) {
        v = options[k];
        this.config[k] = v;
      }
      this.record = simpleFactory(Record, url);
      this.cursor = new Cursor({
        record: this.record,
        speed: this.config.speed,
        looped: this.config.looped,
        on: {
          data: function(timestamp, data) {
            return _this.config.onData(timestamp, data);
          },
          end: function() {
            return _this.config.onEnd();
          },
          error: function(err) {
            return _this.config.onError(err);
          }
        }
      });
      if (this.config.autoplay) {
        this.start();
      }
    }

    Player.prototype.start = function() {
      return this.resume();
    };

    Player.prototype.start = function() {
      return this.cursor.resume();
    };

    Player.prototype.pause = function() {
      return this.cursor.pause();
    };

    return Player;

  })();

}).call(this);
