// Generated by CoffeeScript 1.3.3
(function() {
  var Cursor, Record, Stream, contains, delay, error, inspect, log, moment, simpleFactory, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  Stream = require('stream').Stream;

  moment = require('moment');

  _ref1 = require('./misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains, simpleFactory = _ref1.simpleFactory;

  Record = require('./record');

  Cursor = require('./cursor');

  exports.Recorder = (function() {

    function Recorder(url) {
      var _this = this;
      if (url == null) {
        url = false;
      }
      this.writeAt = __bind(this.writeAt, this);

      this.write = __bind(this.write, this);

      this.record = simpleFactory(Record, url);
      this.record.on('error', function(err) {
        log("SimpleRecorder: underlying record got an error: " + err);
      });
      this.record.on('flushed', function() {
        log("SimpleRecorder: underlying record flushed to disk. We don't care");
      });
    }

    Recorder.prototype.write = function(data, cb) {
      if (cb == null) {
        cb = false;
      }
      return this.record.write(moment(), data, cb);
    };

    Recorder.prototype.writeAt = function(timestamp, data, cb) {
      if (cb == null) {
        cb = false;
      }
      return this.record.write(timestamp, data, cb);
    };

    return Recorder;

  })();

  exports.Player = (function() {

    function Player(url, options) {
      var k, v,
        _this = this;
      this.config = {
        speed: 1.0,
        autoplay: true,
        timestamp: false,
        looped: false,
        onBegin: function() {},
        onData: function(tm, data) {},
        onEnd: function() {},
        onError: function(err) {}
      };
      for (k in options) {
        v = options[k];
        this.config[k] = v;
      }
      this.record = simpleFactory(Record, url);
      this.cursor = new Cursor({
        record: this.record,
        speed: this.config.speed,
        looped: this.config.looped
      });
      this.cursor.on('begin', function() {
        return _this.config.onBegin();
      });
      this.cursor.on('data', function(packet) {
        return _this.emit('data', packet);
      });
      this.cursor.on('end', function() {
        log("CURSOR SENT 'end'");
        _this.emit('end');
        return {
          error: function(err) {
            return _this.config.onError(err);
          }
        };
      });
      if (this.config.autoplay) {
        this.start();
      }
    }

    Player.prototype.start = function() {
      return this.resume();
    };

    Player.prototype.resume = function() {
      return this.cursor.resume();
    };

    Player.prototype.pause = function() {
      return this.cursor.pause();
    };

    return Player;

  })();

}).call(this);
