// Generated by CoffeeScript 1.3.3
(function() {
  var InMemory, contains, delay, error, inspect, log, _ref, _ref1;

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  _ref1 = require('./misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains;

  InMemory = require('./store/memory');

  exports.SimpleFile = (function() {

    function SimpleFile() {}

    return SimpleFile;

  })();

  exports.Redis = (function() {

    function Redis() {}

    return Redis;

  })();

  exports.InMemory = InMemory;

}).call(this);
