// Generated by CoffeeScript 1.3.3
(function() {
  var Cursor, Record, Stream, contains, delay, error, inspect, log, moment, simpleFactory, _, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  Stream = require('stream').Stream;

  _ = require('underscore');

  moment = require('moment');

  _ref1 = require('./misc/toolbox'), delay = _ref1.delay, contains = _ref1.contains, simpleFactory = _ref1.simpleFactory;

  Record = require('./record');

  Cursor = require('./cursor');

  exports.Recorder = (function(_super) {

    __extends(Recorder, _super);

    function Recorder(url) {
      if (url == null) {
        url = "";
      }
      this.writeAt = __bind(this.writeAt, this);

      this.write = __bind(this.write, this);

      this.end = __bind(this.end, this);

      log("StreamRecorder#constructor(" + url + ")");
      this.record = simpleFactory(Record, url);
    }

    Recorder.prototype.end = function(data) {};

    Recorder.prototype.write = function(data, status) {
      if (status == null) {
        status = function() {};
      }
      log("StreamRecorder#write(" + data + ")");
      return this.record.write(moment(), data, status);
    };

    Recorder.prototype.writeAt = function(timestamp, data, status) {
      if (status == null) {
        status = function() {};
      }
      log("StreamRecorder#writeAt(" + timestamp + "," + data + ")");
      return this.record.write(timestamp, data, status);
    };

    return Recorder;

  })(Stream);

  exports.Player = (function(_super) {

    __extends(Player, _super);

    function Player(url, options) {
      this.pause = __bind(this.pause, this);

      this.resume = __bind(this.resume, this);

      var k, v,
        _this = this;
      log("StreamPlayer#constructor(" + url + ")");
      this.config = {
        speed: 1.0,
        autoplay: true,
        timestamp: false,
        looped: false
      };
      for (k in options) {
        v = options[k];
        this.config[k] = v;
      }
      this.record = simpleFactory(Record, url);
      this.cursor = new Cursor({
        record: this.record,
        speed: this.config.speed,
        looped: this.config.looped,
        on: {
          data: function(timestamp, data) {
            return _this.emit('data', data);
          },
          end: function() {
            return _this.emit('end');
          },
          error: function(err) {
            return log("error: " + err);
          }
        }
      });
      if (this.config.autoplay) {
        this.resume();
      }
    }

    Player.prototype.resume = function() {
      log("StreamPlayer#resume()");
      return this.cursor.resume();
    };

    Player.prototype.pause = function() {
      log("StreamPlayer#pause()");
      return this.cursor.pause();
    };

    return Player;

  })(Stream);

}).call(this);
